# Generated by Django 2.1.2 on 2018-10-30 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181029_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 30, 12, 40, 1, 392448, tzinfo=utc)),
        ),
    ]
